# [17] 解釋의 方法, 標準.d2

direction: down

"민법 해석" -> "해석 방법"
"민법 해석" -> "해석 기준"
"민법 해석" -> "해석의 지향점"

"해석 방법" -> "문리해석: 문장의 일반 의미에 따라"
"해석 방법" -> "논리해석: 조문 간 체계적 조화"
"해석 방법" -> "반대해석: 규정된 경우의 반대 결과 인정"
"해석 방법" -> "유추해석: 규정 없을 경우 유사 규정 적용"
"해석 방법" -> "확장해석: 의미 확장"
"해석 방법" -> "축소해석: 의미 제한"
"해석 방법" -> "물론해석: 너무 당연하여 규정 생략"
"해석 방법" -> "변경해석 등 기타"

"해석 기준" -> "법의 목적 중심"
"법의 목적 중심" -> "→ 합목적적 해석"

"해석의 지향점" -> "구체적 타당성"
"해석의 지향점" -> "법적 안정성"

"해석의 지향점" -> "해석 가치의 조화"
"해석 가치의 조화" -> "조화가 어렵지만 필요"
"해석 가치의 조화" -> "충돌 시 법적 안정성이 우선됨"
