# [1] 法秩序의 一般으로서의 民法.d2

direction: down

"사회생활" -> "사회생활의 규범 필요"
"사회생활의 규범 필요" -> "당위의 법칙"
"당위의 법칙" -> "법"
"당위의 법칙" -> "도덕"
"당위의 법칙" -> "관습"
"당위의 법칙" -> "종교"
"법" -> "강제력 있는 규범"
"법" -> "법체계"
"법체계" -> "법질서"
"법질서" -> "민법"
"민법" -> "사법의 일반법 (통설)"
