# [9] 総說.d2

direction: down

"한국 민법의 역사" -> "조선시대까지"
"한국 민법의 역사" -> "일제 치하"
"한국 민법의 역사" -> "광복 이후"
"한국 민법의 역사" -> "1958년 민법전 제정"

"1958년 민법전 제정" -> "법률 제471호 공포"
"1958년 민법전 제정" -> "민법의 성격"

"민법의 성격" -> "계수법적 요소"
"민법의 성격" -> "고유법적 요소"

"계수법적 요소" -> "프랑스 민법 (1804)"
"계수법적 요소" -> "독일 민법 초안 (1888)"
